const LANGUAGES_MAP = {
	"Acehnese (Arabic script)": [
		{ "Xenova/nllb-200-distilled-600M": "ace_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ar" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ar" },
	],
	"Acehnese (Latin script)": [
		{ "Xenova/nllb-200-distilled-600M": "ace_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Afrikaans: [
		{ "Xenova/nllb-200-distilled-600M": "afr_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "af_ZA" },
		{ "Xenova/m2m100_418M": "af" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "af" },
	],
	Akan: [
		{ "Xenova/nllb-200-distilled-600M": "aka_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Amharic: [
		{ "Xenova/nllb-200-distilled-600M": "amh_Ethi" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "am" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "am" },
	],
	Armenian: [
		{ "Xenova/nllb-200-distilled-600M": "hye_Armn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "hy" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "hy" },
	],
	Assamese: [
		{ "Xenova/nllb-200-distilled-600M": "asm_Beng" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Asturian: [
		{ "Xenova/nllb-200-distilled-600M": "ast_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ast" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ast" },
	],
	Awadhi: [
		{ "Xenova/nllb-200-distilled-600M": "awa_Deva" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Ayacucho Quechua": [
		{ "Xenova/nllb-200-distilled-600M": "quy_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Balinese: [
		{ "Xenova/nllb-200-distilled-600M": "ban_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Bambara: [
		{ "Xenova/nllb-200-distilled-600M": "bam_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Banjar (Arabic script)": [
		{ "Xenova/nllb-200-distilled-600M": "bjn_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ar" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ar" },
	],
	"Banjar (Latin script)": [
		{ "Xenova/nllb-200-distilled-600M": "bjn_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Bashkir: [
		{ "Xenova/nllb-200-distilled-600M": "bak_Cyrl" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ba" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ba" },
	],
	Basque: [
		{ "Xenova/nllb-200-distilled-600M": "eus_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Belarusian: [
		{ "Xenova/nllb-200-distilled-600M": "bel_Cyrl" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "be" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "be" },
	],
	Bemba: [
		{ "Xenova/nllb-200-distilled-600M": "bem_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Bengali: [
		{ "Xenova/nllb-200-distilled-600M": "ben_Beng" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "bn_IN" },
		{ "Xenova/m2m100_418M": "bn" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "bn" },
	],
	Bhojpuri: [
		{ "Xenova/nllb-200-distilled-600M": "bho_Deva" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Bosnian: [
		{ "Xenova/nllb-200-distilled-600M": "bos_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "bs" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "bs" },
	],
	Buginese: [
		{ "Xenova/nllb-200-distilled-600M": "bug_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Bulgarian: [
		{ "Xenova/nllb-200-distilled-600M": "bul_Cyrl" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "bg" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "bg" },
	],
	Burmese: [
		{ "Xenova/nllb-200-distilled-600M": "mya_Mymr" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "my_MM" },
		{ "Xenova/m2m100_418M": "my" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "my" },
	],
	Catalan: [
		{ "Xenova/nllb-200-distilled-600M": "cat_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ca" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ca" },
	],
	Cebuano: [
		{ "Xenova/nllb-200-distilled-600M": "ceb_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ceb" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ceb" },
	],
	"Central Atlas Tamazight": [
		{ "Xenova/nllb-200-distilled-600M": "tzm_Tfng" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Central Aymara": [
		{ "Xenova/nllb-200-distilled-600M": "ayr_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Central Kanuri (Arabic script)": [
		{ "Xenova/nllb-200-distilled-600M": "knc_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ar" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ar" },
	],
	"Central Kanuri (Latin script)": [
		{ "Xenova/nllb-200-distilled-600M": "knc_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Central Kurdish": [
		{ "Xenova/nllb-200-distilled-600M": "ckb_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Chhattisgarhi: [
		{ "Xenova/nllb-200-distilled-600M": "hne_Deva" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Chinese (Simplified)": [
		{ "Xenova/nllb-200-distilled-600M": "zho_Hans" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "zh_CN" },
		{ "Xenova/m2m100_418M": "zh" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "zh" },
	],
	"Chinese (Traditional)": [
		{ "Xenova/nllb-200-distilled-600M": "zho_Hant" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "zh_CN" },
		{ "Xenova/m2m100_418M": "zh" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "zh" },
	],
	Chokwe: [
		{ "Xenova/nllb-200-distilled-600M": "cjk_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Crimean Tatar": [
		{ "Xenova/nllb-200-distilled-600M": "crh_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Croatian: [
		{ "Xenova/nllb-200-distilled-600M": "hrv_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "hr_HR" },
		{ "Xenova/m2m100_418M": "hr" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "hr" },
	],
	Czech: [
		{ "Xenova/nllb-200-distilled-600M": "ces_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "cs_CZ" },
		{ "Xenova/m2m100_418M": "cs" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "cs" },
	],
	Danish: [
		{ "Xenova/nllb-200-distilled-600M": "dan_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "da" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "da" },
	],
	Dari: [
		{ "Xenova/nllb-200-distilled-600M": "prs_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Dutch: [
		{ "Xenova/nllb-200-distilled-600M": "nld_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "nl_XX" },
		{ "Xenova/m2m100_418M": "nl" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "nl" },
	],
	Dyula: [
		{ "Xenova/nllb-200-distilled-600M": "dyu_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Dzongkha: [
		{ "Xenova/nllb-200-distilled-600M": "dzo_Tibt" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Eastern Panjabi": [
		{ "Xenova/nllb-200-distilled-600M": "pan_Guru" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "pa" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "pa" },
	],
	"Eastern Yiddish": [
		{ "Xenova/nllb-200-distilled-600M": "ydd_Hebr" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "yi" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "yi" },
	],
	"Egyptian Arabic": [
		{ "Xenova/nllb-200-distilled-600M": "arz_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ar" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ar" },
	],
	English: [
		{ "Xenova/nllb-200-distilled-600M": "eng_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "en_XX" },
		{ "Xenova/m2m100_418M": "en" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "en" },
	],
	Esperanto: [
		{ "Xenova/nllb-200-distilled-600M": "epo_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Estonian: [
		{ "Xenova/nllb-200-distilled-600M": "est_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "et_EE" },
		{ "Xenova/m2m100_418M": "et" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "et" },
	],
	Ewe: [
		{ "Xenova/nllb-200-distilled-600M": "ewe_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Faroese: [
		{ "Xenova/nllb-200-distilled-600M": "fao_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Fijian: [
		{ "Xenova/nllb-200-distilled-600M": "fij_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Finnish: [
		{ "Xenova/nllb-200-distilled-600M": "fin_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "fi_FI" },
		{ "Xenova/m2m100_418M": "fi" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "fi" },
	],
	Fon: [
		{ "Xenova/nllb-200-distilled-600M": "fon_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	French: [
		{ "Xenova/nllb-200-distilled-600M": "fra_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "fr_XX" },
		{ "Xenova/m2m100_418M": "fr" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "fr" },
	],
	Friulian: [
		{ "Xenova/nllb-200-distilled-600M": "fur_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Galician: [
		{ "Xenova/nllb-200-distilled-600M": "glg_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "gl_ES" },
		{ "Xenova/m2m100_418M": "gl" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "gl" },
	],
	Ganda: [
		{ "Xenova/nllb-200-distilled-600M": "lug_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "lg" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "lg" },
	],
	Georgian: [
		{ "Xenova/nllb-200-distilled-600M": "kat_Geor" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "ka_GE" },
		{ "Xenova/m2m100_418M": "ka" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ka" },
	],
	German: [
		{ "Xenova/nllb-200-distilled-600M": "deu_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "de_DE" },
		{ "Xenova/m2m100_418M": "de" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "de" },
	],
	Greek: [
		{ "Xenova/nllb-200-distilled-600M": "ell_Grek" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "el" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "el" },
	],
	Guarani: [
		{ "Xenova/nllb-200-distilled-600M": "grn_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Gujarati: [
		{ "Xenova/nllb-200-distilled-600M": "guj_Gujr" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "gu_IN" },
		{ "Xenova/m2m100_418M": "gu" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "gu" },
	],
	"Haitian Creole": [
		{ "Xenova/nllb-200-distilled-600M": "hat_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ht" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ht" },
	],
	"Halh Mongolian": [
		{ "Xenova/nllb-200-distilled-600M": "khk_Cyrl" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "mn_MN" },
		{ "Xenova/m2m100_418M": "mn" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "mn" },
	],
	Hausa: [
		{ "Xenova/nllb-200-distilled-600M": "hau_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ha" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ha" },
	],
	Hebrew: [
		{ "Xenova/nllb-200-distilled-600M": "heb_Hebr" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "he_IL" },
		{ "Xenova/m2m100_418M": "he" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "he" },
	],
	Hindi: [
		{ "Xenova/nllb-200-distilled-600M": "hin_Deva" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "hi_IN" },
		{ "Xenova/m2m100_418M": "hi" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "hi" },
	],
	Hungarian: [
		{ "Xenova/nllb-200-distilled-600M": "hun_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "hu" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "hu" },
	],
	Icelandic: [
		{ "Xenova/nllb-200-distilled-600M": "isl_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "is" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "is" },
	],
	Igbo: [
		{ "Xenova/nllb-200-distilled-600M": "ibo_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ig" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ig" },
	],
	Ilocano: [
		{ "Xenova/nllb-200-distilled-600M": "ilo_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ilo" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ilo" },
	],
	Indonesian: [
		{ "Xenova/nllb-200-distilled-600M": "ind_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "id_ID" },
		{ "Xenova/m2m100_418M": "id" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "id" },
	],
	Irish: [
		{ "Xenova/nllb-200-distilled-600M": "gle_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ga" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ga" },
	],
	Italian: [
		{ "Xenova/nllb-200-distilled-600M": "ita_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "it_IT" },
		{ "Xenova/m2m100_418M": "it" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "it" },
	],
	Japanese: [
		{ "Xenova/nllb-200-distilled-600M": "jpn_Jpan" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "ja_XX" },
		{ "Xenova/m2m100_418M": "ja" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ja" },
	],
	Javanese: [
		{ "Xenova/nllb-200-distilled-600M": "jav_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "jv" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "jv" },
	],
	Jingpho: [
		{ "Xenova/nllb-200-distilled-600M": "kac_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Kabiyè: [
		{ "Xenova/nllb-200-distilled-600M": "kbp_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Kabuverdianu: [
		{ "Xenova/nllb-200-distilled-600M": "kea_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Kabyle: [
		{ "Xenova/nllb-200-distilled-600M": "kab_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Kamba: [
		{ "Xenova/nllb-200-distilled-600M": "kam_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Kannada: [
		{ "Xenova/nllb-200-distilled-600M": "kan_Knda" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "kn" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "kn" },
	],
	"Kashmiri (Arabic script)": [
		{ "Xenova/nllb-200-distilled-600M": "kas_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ar" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ar" },
	],
	"Kashmiri (Devanagari script)": [
		{ "Xenova/nllb-200-distilled-600M": "kas_Deva" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Kazakh: [
		{ "Xenova/nllb-200-distilled-600M": "kaz_Cyrl" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "kk_KZ" },
		{ "Xenova/m2m100_418M": "kk" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "kk" },
	],
	Khmer: [
		{ "Xenova/nllb-200-distilled-600M": "khm_Khmr" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "km_KH" },
		{ "Xenova/m2m100_418M": "km" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "km" },
	],
	Kikongo: [
		{ "Xenova/nllb-200-distilled-600M": "kon_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Kikuyu: [
		{ "Xenova/nllb-200-distilled-600M": "kik_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Kimbundu: [
		{ "Xenova/nllb-200-distilled-600M": "kmb_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Kinyarwanda: [
		{ "Xenova/nllb-200-distilled-600M": "kin_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Korean: [
		{ "Xenova/nllb-200-distilled-600M": "kor_Hang" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "ko_KR" },
		{ "Xenova/m2m100_418M": "ko" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ko" },
	],
	Kyrgyz: [
		{ "Xenova/nllb-200-distilled-600M": "kir_Cyrl" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Lao: [
		{ "Xenova/nllb-200-distilled-600M": "lao_Laoo" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "lo" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "lo" },
	],
	Latgalian: [
		{ "Xenova/nllb-200-distilled-600M": "ltg_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Ligurian: [
		{ "Xenova/nllb-200-distilled-600M": "lij_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Limburgish: [
		{ "Xenova/nllb-200-distilled-600M": "lim_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Lingala: [
		{ "Xenova/nllb-200-distilled-600M": "lin_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ln" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ln" },
	],
	Lithuanian: [
		{ "Xenova/nllb-200-distilled-600M": "lit_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "lt_LT" },
		{ "Xenova/m2m100_418M": "lt" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "lt" },
	],
	Lombard: [
		{ "Xenova/nllb-200-distilled-600M": "lmo_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Luba-Kasai": [
		{ "Xenova/nllb-200-distilled-600M": "lua_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Luo: [
		{ "Xenova/nllb-200-distilled-600M": "luo_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Luxembourgish: [
		{ "Xenova/nllb-200-distilled-600M": "ltz_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "lb" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "lb" },
	],
	Macedonian: [
		{ "Xenova/nllb-200-distilled-600M": "mkd_Cyrl" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "mk_MK" },
		{ "Xenova/m2m100_418M": "mk" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "mk" },
	],
	Magahi: [
		{ "Xenova/nllb-200-distilled-600M": "mag_Deva" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Maithili: [
		{ "Xenova/nllb-200-distilled-600M": "mai_Deva" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Malayalam: [
		{ "Xenova/nllb-200-distilled-600M": "mal_Mlym" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "ml_IN" },
		{ "Xenova/m2m100_418M": "ml" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ml" },
	],
	Maltese: [
		{ "Xenova/nllb-200-distilled-600M": "mlt_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Maori: [
		{ "Xenova/nllb-200-distilled-600M": "mri_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Marathi: [
		{ "Xenova/nllb-200-distilled-600M": "mar_Deva" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "mr_IN" },
		{ "Xenova/m2m100_418M": "mr" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "mr" },
	],
	"Meitei (Bengali script)": [
		{ "Xenova/nllb-200-distilled-600M": "mni_Beng" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "bn" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "bn" },
	],
	"Mesopotamian Arabic": [
		{ "Xenova/nllb-200-distilled-600M": "acm_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ar" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ar" },
	],
	"Minangkabau (Arabic script)": [
		{ "Xenova/nllb-200-distilled-600M": "min_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ar" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ar" },
	],
	"Minangkabau (Latin script)": [
		{ "Xenova/nllb-200-distilled-600M": "min_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Mizo: [
		{ "Xenova/nllb-200-distilled-600M": "lus_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Modern Standard Arabic (Romanized)": [
		{ "Xenova/nllb-200-distilled-600M": "arb_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ar" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ar" },
	],
	"Modern Standard Arabic": [
		{ "Xenova/nllb-200-distilled-600M": "arb_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ar" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ar" },
	],
	"Moroccan Arabic": [
		{ "Xenova/nllb-200-distilled-600M": "ary_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ar" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ar" },
	],
	Mossi: [
		{ "Xenova/nllb-200-distilled-600M": "mos_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Najdi Arabic": [
		{ "Xenova/nllb-200-distilled-600M": "ars_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ar" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ar" },
	],
	Nepali: [
		{ "Xenova/nllb-200-distilled-600M": "npi_Deva" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "ne_NP" },
		{ "Xenova/m2m100_418M": "ne" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ne" },
	],
	"Nigerian Fulfulde": [
		{ "Xenova/nllb-200-distilled-600M": "fuv_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"North Azerbaijani": [
		{ "Xenova/nllb-200-distilled-600M": "azj_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "az_AZ" },
		{ "Xenova/m2m100_418M": "az" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "az" },
	],
	"North Levantine Arabic": [
		{ "Xenova/nllb-200-distilled-600M": "apc_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ar" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ar" },
	],
	"Northern Kurdish": [
		{ "Xenova/nllb-200-distilled-600M": "kmr_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Northern Sotho": [
		{ "Xenova/nllb-200-distilled-600M": "nso_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ns" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ns" },
	],
	"Northern Uzbek": [
		{ "Xenova/nllb-200-distilled-600M": "uzn_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "uz" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "uz" },
	],
	"Norwegian Bokmål": [
		{ "Xenova/nllb-200-distilled-600M": "nob_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "no" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "no" },
	],
	"Norwegian Nynorsk": [
		{ "Xenova/nllb-200-distilled-600M": "nno_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "no" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "no" },
	],
	Nuer: [
		{ "Xenova/nllb-200-distilled-600M": "nus_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Nyanja: [
		{ "Xenova/nllb-200-distilled-600M": "nya_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Occitan: [
		{ "Xenova/nllb-200-distilled-600M": "oci_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "oc" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "oc" },
	],
	Odia: [
		{ "Xenova/nllb-200-distilled-600M": "ory_Orya" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Pangasinan: [
		{ "Xenova/nllb-200-distilled-600M": "pag_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Papiamento: [
		{ "Xenova/nllb-200-distilled-600M": "pap_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Plateau Malagasy": [
		{ "Xenova/nllb-200-distilled-600M": "plt_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "mg" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "mg" },
	],
	Polish: [
		{ "Xenova/nllb-200-distilled-600M": "pol_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "pl_PL" },
		{ "Xenova/m2m100_418M": "pl" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "pl" },
	],
	Portuguese: [
		{ "Xenova/nllb-200-distilled-600M": "por_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "pt_XX" },
		{ "Xenova/m2m100_418M": "pt" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "pt" },
	],
	Romanian: [
		{ "Xenova/nllb-200-distilled-600M": "ron_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "ro_RO" },
		{ "Xenova/m2m100_418M": "ro" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ro" },
	],
	Rundi: [
		{ "Xenova/nllb-200-distilled-600M": "run_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Russian: [
		{ "Xenova/nllb-200-distilled-600M": "rus_Cyrl" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "ru_RU" },
		{ "Xenova/m2m100_418M": "ru" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ru" },
	],
	Samoan: [
		{ "Xenova/nllb-200-distilled-600M": "smo_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Sango: [
		{ "Xenova/nllb-200-distilled-600M": "sag_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Sanskrit: [
		{ "Xenova/nllb-200-distilled-600M": "san_Deva" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Santali: [
		{ "Xenova/nllb-200-distilled-600M": "sat_Olck" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Sardinian: [
		{ "Xenova/nllb-200-distilled-600M": "srd_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Scottish Gaelic": [
		{ "Xenova/nllb-200-distilled-600M": "gla_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "gd" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "gd" },
	],
	Serbian: [
		{ "Xenova/nllb-200-distilled-600M": "srp_Cyrl" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "sr" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "sr" },
	],
	Shan: [
		{ "Xenova/nllb-200-distilled-600M": "shn_Mymr" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Shona: [
		{ "Xenova/nllb-200-distilled-600M": "sna_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Sicilian: [
		{ "Xenova/nllb-200-distilled-600M": "scn_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Silesian: [
		{ "Xenova/nllb-200-distilled-600M": "szl_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Sindhi: [
		{ "Xenova/nllb-200-distilled-600M": "snd_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "sd" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "sd" },
	],
	Sinhala: [
		{ "Xenova/nllb-200-distilled-600M": "sin_Sinh" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "si_LK" },
		{ "Xenova/m2m100_418M": "si" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "si" },
	],
	Slovak: [
		{ "Xenova/nllb-200-distilled-600M": "slk_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "sk" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "sk" },
	],
	Slovenian: [
		{ "Xenova/nllb-200-distilled-600M": "slv_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "sl_SI" },
		{ "Xenova/m2m100_418M": "sl" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "sl" },
	],
	Somali: [
		{ "Xenova/nllb-200-distilled-600M": "som_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "so" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "so" },
	],
	"South Azerbaijani": [
		{ "Xenova/nllb-200-distilled-600M": "azb_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "az_AZ" },
		{ "Xenova/m2m100_418M": "az" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "az" },
	],
	"South Levantine Arabic": [
		{ "Xenova/nllb-200-distilled-600M": "ajp_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ar" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ar" },
	],
	"Southern Pashto": [
		{ "Xenova/nllb-200-distilled-600M": "pbt_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "ps_AF" },
		{ "Xenova/m2m100_418M": "ps" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ps" },
	],
	"Southern Sotho": [
		{ "Xenova/nllb-200-distilled-600M": "sot_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Southwestern Dinka": [
		{ "Xenova/nllb-200-distilled-600M": "dik_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Spanish: [
		{ "Xenova/nllb-200-distilled-600M": "spa_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "es_XX" },
		{ "Xenova/m2m100_418M": "es" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "es" },
	],
	"Standard Latvian": [
		{ "Xenova/nllb-200-distilled-600M": "lvs_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "lv_LV" },
		{ "Xenova/m2m100_418M": "lv" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "lv" },
	],
	"Standard Malay": [
		{ "Xenova/nllb-200-distilled-600M": "zsm_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ms" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ms" },
	],
	"Standard Tibetan": [
		{ "Xenova/nllb-200-distilled-600M": "bod_Tibt" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Sundanese: [
		{ "Xenova/nllb-200-distilled-600M": "sun_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "su" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "su" },
	],
	Swahili: [
		{ "Xenova/nllb-200-distilled-600M": "swh_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "sw_KE" },
		{ "Xenova/m2m100_418M": "sw" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "sw" },
	],
	Swati: [
		{ "Xenova/nllb-200-distilled-600M": "ssw_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ss" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ss" },
	],
	Swedish: [
		{ "Xenova/nllb-200-distilled-600M": "swe_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "sv_SE" },
		{ "Xenova/m2m100_418M": "sv" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "sv" },
	],
	Tagalog: [
		{ "Xenova/nllb-200-distilled-600M": "tgl_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "tl_XX" },
		{ "Xenova/m2m100_418M": "tl" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "tl" },
	],
	Tajik: [
		{ "Xenova/nllb-200-distilled-600M": "tgk_Cyrl" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Tamasheq (Latin script)": [
		{ "Xenova/nllb-200-distilled-600M": "taq_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Tamasheq (Tifinagh script)": [
		{ "Xenova/nllb-200-distilled-600M": "taq_Tfng" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Tamil: [
		{ "Xenova/nllb-200-distilled-600M": "tam_Taml" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "ta_IN" },
		{ "Xenova/m2m100_418M": "ta" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ta" },
	],
	Tatar: [
		{ "Xenova/nllb-200-distilled-600M": "tat_Cyrl" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Ta’izzi-Adeni Arabic": [
		{ "Xenova/nllb-200-distilled-600M": "acq_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ar" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ar" },
	],
	Telugu: [
		{ "Xenova/nllb-200-distilled-600M": "tel_Telu" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "te_IN" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Thai: [
		{ "Xenova/nllb-200-distilled-600M": "tha_Thai" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "th_TH" },
		{ "Xenova/m2m100_418M": "th" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "th" },
	],
	Tigrinya: [
		{ "Xenova/nllb-200-distilled-600M": "tir_Ethi" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Tok Pisin": [
		{ "Xenova/nllb-200-distilled-600M": "tpi_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Tosk Albanian": [
		{ "Xenova/nllb-200-distilled-600M": "als_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "sq" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "sq" },
	],
	Tsonga: [
		{ "Xenova/nllb-200-distilled-600M": "tso_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Tswana: [
		{ "Xenova/nllb-200-distilled-600M": "tsn_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "tn" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "tn" },
	],
	Tumbuka: [
		{ "Xenova/nllb-200-distilled-600M": "tum_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Tunisian Arabic": [
		{ "Xenova/nllb-200-distilled-600M": "aeb_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ar" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ar" },
	],
	Turkish: [
		{ "Xenova/nllb-200-distilled-600M": "tur_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "tr_TR" },
		{ "Xenova/m2m100_418M": "tr" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "tr" },
	],
	Turkmen: [
		{ "Xenova/nllb-200-distilled-600M": "tuk_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Twi: [
		{ "Xenova/nllb-200-distilled-600M": "twi_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Ukrainian: [
		{ "Xenova/nllb-200-distilled-600M": "ukr_Cyrl" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "uk_UA" },
		{ "Xenova/m2m100_418M": "uk" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "uk" },
	],
	Umbundu: [
		{ "Xenova/nllb-200-distilled-600M": "umb_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Urdu: [
		{ "Xenova/nllb-200-distilled-600M": "urd_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "ur_PK" },
		{ "Xenova/m2m100_418M": "ur" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ur" },
	],
	Uyghur: [
		{ "Xenova/nllb-200-distilled-600M": "uig_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Venetian: [
		{ "Xenova/nllb-200-distilled-600M": "vec_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Vietnamese: [
		{ "Xenova/nllb-200-distilled-600M": "vie_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "vi_VN" },
		{ "Xenova/m2m100_418M": "vi" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "vi" },
	],
	Waray: [
		{ "Xenova/nllb-200-distilled-600M": "war_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Welsh: [
		{ "Xenova/nllb-200-distilled-600M": "cym_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "cy" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "cy" },
	],
	"West Central Oromo": [
		{ "Xenova/nllb-200-distilled-600M": "gaz_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	"Western Persian": [
		{ "Xenova/nllb-200-distilled-600M": "pes_Arab" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "fa_IR" },
		{ "Xenova/m2m100_418M": "fa" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "fa" },
	],
	Wolof: [
		{ "Xenova/nllb-200-distilled-600M": "wol_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "wo" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "wo" },
	],
	Xhosa: [
		{ "Xenova/nllb-200-distilled-600M": "xho_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "xh_ZA" },
		{ "Xenova/m2m100_418M": "xh" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "xh" },
	],
	Yoruba: [
		{ "Xenova/nllb-200-distilled-600M": "yor_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "yo" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "yo" },
	],
	"Yue Chinese": [
		{ "Xenova/nllb-200-distilled-600M": "yue_Hant" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "" },
	],
	Zulu: [
		{ "Xenova/nllb-200-distilled-600M": "zul_Latn" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "zu" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "zu" },
	],
	Oriya: [
		{ "Xenova/nllb-200-distilled-600M": "" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "or" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "or" },
	],
	Moldovan: [
		{ "Xenova/nllb-200-distilled-600M": "" },
		{ "Xenova/mbart-large-50-many-to-many-mmt": "" },
		{ "Xenova/m2m100_418M": "ro" },
		{ "CXDuncan/madlad400-3b-mt-optimized-quantized-onnx": "ro" },
	],
};

module.exports = { LANGUAGES_MAP };
